ncourses/applications/blog/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para la aplicacion curso

    #url para ver informacion de curso
    url(
        r'^articulos-y-tutoriales-en-ingenieria/(?P<category>[-\w]+)/$',
        views.BlogListView.as_view(),
        name='blog-list'
    ),
    #url para ver blog-articulo
    url(
        r'^ver-blogs-de-ingenieria/(?P<slug>[-\w]+)/$',
        views.BlogDetailView.as_view(),
        name='blog-detail'
    )
]

ncourses/applications/cursos/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para la aplicacion curso

    #url para ver informacion de curso
    url(
        r'^detalle-del-curso/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.CourseDetailView.as_view(),
        name='course-detail'
    ),

    # urls para vista buscar curso
    url(
        r'^buscar-curso/(?P<category>[-\w]+)/$',
        views.CoursesSearchView.as_view(),
        name='course-search'
    ),
]

ncourses/applications/home/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para la aplicacion home
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    #url para registrar postulantes
    url(
        r'^dictar-cursos-en-ademmy/nuevo-postulante/$',
        views.PostulantCreateView.as_view(),
        name='home-nuevo_postulante'
    ),
    url(
        r'^cursos-online-de-ingenieria/bienvenido/$',
        views.TarjetaView.as_view(),
        name='home-tarjeta'
    ),
    #
    url(
        r'^templates/$',
        views.HomeView.as_view(),
        name='templates'
    ),
]

ncourses/applications/users/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para registrar usuarios
    url(
        r'^registro/$',
        views.UserCreateView.as_view(),
        name='user-add'
    ),
    #url para login de usuarios
    url(
        r'^login/$',
        views.LogIn.as_view(),
        name='user-login'
    ),
    #url para cerrar sesion
    url(
        r'^salir/$',
        views.LogoutView.as_view(),
        name='logout'
    ),
    #url para redireccion
    url(
        r'^redirect/(?P<pk>\d+)/$',
        views.RedirectView.as_view(),
        name='redirect'
    ),
]

ncourses/ncourses/urls.py
"""ncourses URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # urls para la aplicacion home
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.home.urls', namespace="home_app")),
    url(r'^', include('applications.cursos.urls', namespace="cursos_app")),
    url(r'^', include('applications.topicos.urls', namespace="topicos_app")),
    url(r'^', include('applications.matriculas.urls', namespace="matriculas_app")),
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncourses/templates/include/header.html
<header>
  <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="example-menu"></button>
    <div class="title-bar-title">Menu</div>
  </div>

  <div class="top-bar header" id="example-menu">
    <div class="top-bar-left">
      <h1 class="header-logo">Ademmy</h1>
    </div>
    <div class="top-bar-right">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-item">
          <a href="{% url 'home_app:index' %}" class="menu-item__link">Inicio</a>
        </li>
        <li class="menu-item"><a href="{% url 'home_app:home-nuevo_postulante' %}" class="menu-item__link">Enseña</a></li>
        <li class="menu-item"><a href="{% url 'blog_app:blog-list' 'todos' %}" class="menu-item__link">Blog</a></li>
        <li class="menu-item"><a href="{% url 'cursos_app:course-search' 'todos' %}" class="button menu-item__btn">Cursos</a></li>

        {% if user.is_authenticated %}
          <li class="menu-item__salir"><a href="{% url 'users_app:logout' %}" class="user-menu-item__link__active">Salir</a></li>
        {% else %}
          <li class="menu-item"><a href="{% url 'users_app:user-login' %}" class="button menu-item__btn__login">Ingresar</a></li>
        {% endif %}

      </ul>
    </div>
  </div>
</header>

ncourses/templates/include/menu.html
{% load  staticfiles %}
<div class="user-main-menu">
  <div id="togle-menu" class="icon-menu">
    <i class="fa fa-bars" aria-hidden="true"></i>
  </div>
  <div id="nav-menu" class="user-nav-menu">
    <ul class="user-menu-main">
      <li class="menu-user">
        <img src="{% static 'img/avatar.jpg' %}" alt="" class="menu-user__img">
        <p class="menu-user__name">{{user.first_name}}</p>
      </li>
      <li class="user-menu-item">
        <i class="fa fa-home" aria-hidden="true"></i>
        <a href="/" class="user-menu-item__link">Inicio</a>
      </li>
      <li class="user-menu-item">
        <i class="fa fa-book" aria-hidden="true"></i>
        <a href="/" class="user-menu-item__link">Mis Cursos</a>
      </li>
      <li class="user-menu-item">
        <i class="fa fa-search" aria-hidden="true"></i>
        <a href="{% url 'cursos_app:course-search' 'todos' %}" class="user-menu-item__link">Explorar Cursos</a>
      </li>
      <li class="user-menu-item">
        <i class="fa fa-globe" aria-hidden="true"></i>
        <a href="#" class="user-menu-item__link">Blog</a>
      </li>
      <li class="user-menu-item">
        <i class="fa fa-question-circle" aria-hidden="true"></i>
        <a href="#" class="user-menu-item__link">Preguntas</a>
      </li>
      <li class="user-menu-item">
        <i class="fa fa-sign-out" aria-hidden="true"></i>
        <a href="{% url 'users_app:logout' %}" class="user-menu-item__link__active">Salir</a>
      </li>
    </ul>
  </div>
  <a href="{% url 'users_app:logout' %}" title="salir" class="icon-logout"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
</div>
<div class="space_head">

</div>