ncourses/applications/cursos/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para la aplicacion curso

    #url para ver informacion de curso
    url(
        r'^detalle-del-curso/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.CourseDetailView.as_view(),
        name='course-detail'
    ),

    # urls para vista buscar curso
    url(
        r'^buscar-curso/(?P<category>[-\w]+)/$',
        views.CoursesSearchView.as_view(),
        name='course-search'
    ),
]

ncourses/applications/matriculas/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    #url para dasboard de usuarios
    url(
        r'^dasboard/$',
        views.DashboarUserView.as_view(),
        name='matricula-dashboard'
    ),

    # urls para pantalla pre-inscripcion
    url(
        r'^pre-inscripcion/(?P<pk>\d+)/$',
        views.PreRegistrationView.as_view(),
        name='matricula-preinscripcion'
    ),
]

ncourses/applications/topicos/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para la aplicacion home
    url(
        r'^temas-de-curso/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.TopicoByCourseView.as_view(),
        name='topicos-by_course'
    ),
    # urls para ver una clase
    url(
        r'^cursos-clase/(?P<pk>\d+)/(?P<curso>\d+)/$',
        views.TopicoDetailView.as_view(),
        name='topicos-clase_view'
    ),
]

ncourses/applications/users/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para registrar usuarios
    url(
        r'^registro/$',
        views.UserCreateView.as_view(),
        name='user-add'
    ),
    #url para login de usuarios
    url(
        r'^login/$',
        views.LogIn.as_view(),
        name='user-login'
    ),
    #url para cerrar sesion
    url(
        r'^salir/$',
        views.LogoutView.as_view(),
        name='logout'
    ),
    #url para redireccion
    url(
        r'^redirect/(?P<pk>\d+)/$',
        views.RedirectView.as_view(),
        name='redirect'
    ),
]

ncourses/ncourses/urls.py
"""ncourses URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # urls para la aplicacion home
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.home.urls', namespace="home_app")),
    url(r'^', include('applications.cursos.urls', namespace="cursos_app")),
    url(r'^', include('applications.topicos.urls', namespace="topicos_app")),
    url(r'^', include('applications.matriculas.urls', namespace="matriculas_app")),
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncourses/applications/cursos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


# standard library
from datetime import timedelta, datetime


# third-party
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField


from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save


#applications miscelanea
from applications.miscelanea.models import (
    Category,
    Tag,
    Recomendation
)

#app user
from applications.users.models import Teacher


#local
from .signals import save_url_image
from .managers import CourseManager


@python_2_unicode_compatible
class Course(TimeStampedModel):
    """ modelo para Cursos """

    NIVEL_CHOICES = (
        ('0', 'Basico'),
        ('1', 'Intermedio'),
        ('2', 'Avanzado'),
    )
    #
    name = models.CharField(
        'Nombre Curso',
        max_length=100,
    )
    category = models.ForeignKey(
        Category,
        related_name='Categoria'
    )
    price = models.DecimalField(
        'Precio',
        max_digits=10,
        decimal_places=3,
    )
    video = models.URLField(
        'Video introductorio',
        blank=True
    )
    image = models.ImageField(
        upload_to='curso',
        verbose_name='imagen_curso',
        blank=True,
        null=True,
    )
    image_url = models.URLField(blank=True)
    description_short = models.TextField(
        'Descripcion corta',
        blank=True,
    )
    description_large = RichTextUploadingField(
        'Descripcion larga',
        null=True,
        blank=True,
    )
    resume = RichTextUploadingField(
        'Resumen',
        null=True,
        blank=True,
    )
    recomendation = models.ForeignKey(
        Recomendation,
        related_name='Recomendacion',
    )
    teacher = models.ForeignKey(
        Teacher,
        related_name='userio_profesor',
        blank=True,
        null=True,
    )
    state = models.BooleanField('Publicar',default=False)
    point = models.IntegerField('Puntaje',default=0)
    visit = models.IntegerField('Visitas',default=0)
    tags = models.ManyToManyField(Tag)
    nivel = models.CharField('Nivel', max_length=1, choices=NIVEL_CHOICES)
    slug = models.SlugField(editable=False, max_length=400)

    objects = CourseManager()

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

    def __str__(self):
        return self.name

    #funcion para validar campos
    def clean(self):
        #verificams que almenos image or image_upload se ingrese
        if ((self.image_url == None) and (self.image == None)):
            raise ValidationError(
                {'image':'Ingrese url de imagen o cargue la imagen de su ordenador'}
            )
        else:
            print 'CORRECTO'

    #funcion que se ejecuta al guardar
    def save(self, *args, **kwargs):
        #cambiammos el formato de video
        video = self.video.split('/')
        self.video = "https://www.youtube.com/embed/"+video[3]
        if not self.id:
            # calculamos el total de segundos de la hora actual
            now = datetime.now()
            total_time = timedelta(
                hours=now.hour,
                minutes=now.minute,
                seconds=now.second
            )
            seconds = int(total_time.total_seconds())
            slug_unique = '%s %s' % (self.name, str(seconds))
        else:
            seconds = self.slug.split('-')[-1]  # recuperamos los segundos
            slug_unique = '%s %s' % (self.name, str(seconds))

        self.slug = slugify(slug_unique)
        #
        super(Course, self).save(*args, **kwargs)

ncourses/applications/matriculas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


# standard library
from datetime import timedelta, datetime


# third-party
from model_utils.models import TimeStampedModel
#
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save

#app Cursos
from applications.cursos.models import Course

#local
from .managers import RegistrationManager


@python_2_unicode_compatible
class Banco(TimeStampedModel):
    """ Bancos registrados"""

    name = models.CharField(
        'Nombre del banco',
        blank=True,
        max_length=100
    )

    class Meta:
        verbose_name = 'Banco'
        verbose_name_plural = 'Bancos'

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Registration(TimeStampedModel):
    """ modelo para Registrar matriculas """

    course = models.ForeignKey(
        Course,
        related_name='matricula_curso',
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='alumno_curso',
        editable=False,
    )
    amount = models.DecimalField(
        'monto',
        max_digits=10,
        decimal_places=3,
        default=0,
        editable=False
    )
    banco = models.ForeignKey(
        Banco,
        related_name='banco',
        null=True,
    )
    cod_transaction = models.CharField(
        'Codigo de transaccion',
        blank=True,
        max_length=50
    )
    date_payment = models.DateTimeField(
        'Fecha Pago',
        blank=True,
        null=True
    )
    discount = models.BooleanField('con descuento',default=False)
    amount_discount = models.DecimalField(
        'Porcentaje Descuento',
        max_digits=4,
        decimal_places=1,
        default=0,
    )
    activate = models.BooleanField('Activado',default=False)
    anulate = models.BooleanField('Anulado',default=False)
    user_activate = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        editable=False,
    )

    objects = RegistrationManager()

    class Meta:
        unique_together = ("course", "user")
        verbose_name = 'Maticula'
        verbose_name_plural = 'matriculas'

    def __str__(self):
        return str(self.user.first_name)


    #funcion que se ejecuta al guardar
    def save(self, *args, **kwargs):
        #guardamos monto del curso
        curso = self.course
        self.amount = curso.price
        #verificamos si se activo
        # if self.activate:
        #     self.user_activate = self.request.user

        super(Registration, self).save(*args, **kwargs)

ncourses/applications/matriculas/forms.py
# -*- encoding: utf-8 -*-
from django import forms

#
from .models import Registration


#
class PreRegistrationForm(forms.ModelForm):
    """ formulario para registro de numero de deposito """

    class Meta:
        model = Registration
        fields = (
            'banco',
            'cod_transaction',
        )
        widgets = {
            'cod_transaction': forms.TextInput(
                attrs={
                    'placeholder': 'Numero de Transaccion',
                    'class':'payment-content__form__input',
                }
            ),
            'banco': forms.Select(
                attrs={
                    'class':'payment-content__form__select',
                }
            ),
        }

ncourses/applications/matriculas/views.py
# -*- coding: utf-8 -*-

# django
from django.views.generic import (
    DetailView,
    TemplateView,
    DeleteView,
    UpdateView,
    ListView,
    View,
)
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect

#app course
from applications.cursos.models import Course

#forms
from .forms import PreRegistrationForm
#modelos
from .models import Registration


class DashboarUserView(TemplateView):
    template_name = 'matriculas/index.html'

    def get_context_data(self, **kwargs):
        context = super(DashboarUserView, self).get_context_data(**kwargs)
        context['pendiente_courses'] = Registration.objects.pendiente_courses_by_user(
            self.request.user
        )
        context['my_courses'] = Registration.objects.courses_by_user(
            self.request.user
        )
        context['relation_courses'] = Course.objects.other_courses()
        return context


class PreRegistrationView(FormView):
    """ vista que registra el codigo de deposito de una matricula """

    template_name = 'matriculas/pre-registro.html'
    form_class = PreRegistrationForm
    success_url = reverse_lazy('matriculas_app:matricula-dashboard')

    def get_context_data(self, **kwargs):
        context = super(PreRegistrationView, self).get_context_data(**kwargs)
        pk_curso = self.kwargs.get('pk', 0)
        context['curso'] = Course.objects.get(pk=pk_curso)
        return context

    def form_valid(self, form):
        #recuperamos la matricula
        pk_curso = self.kwargs.get('pk', 0)
        usuario = self.request.user
        #
        matricula = Registration.objects.get(
            course__pk=pk_curso,
            user=usuario,
        )
        #actualizamos los datos
        matricula.banco = form.cleaned_data['banco']
        matricula.cod_transaction = form.cleaned_data['cod_transaction']
        matricula.save()
        print '====codigo de banco guardado correctamente===='
        return super(PreRegistrationView, self).form_valid(form)

ncourses/templates/matriculas/base_matriculas.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/scrips.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
{% endblock js %}

ncourses/templates/matriculas/index.html
{% extends "matriculas/base_matriculas.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Ademmy cursos online
{% endblock %}

{% block description %}
  {{user.first_name}} - {{user.last_name}}
{% endblock %}

{% block content %}
  {% include "include/menu.html" %}
  <div class="grid-container">
    <!-- cursos que tienen solicitud pendiente -->
    <div class="courses-solicitude">
      <div class="user-cursos__head">
        <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
        <p class="user-cursos__head__title">Cursos que solicite inscripcion</p>
      </div>
      <div class="grid-x">
        {% for pc in pendiente_courses  %}
        <div class="cell shrink courses-solicitude__item">
          <a href="{% url 'users_app:redirect' pc.course.pk %}" class="courses-solicitude__item__link">{{pc.course.name}}</a>
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- fin cursos que tienen solicitud pendiente -->

    <!-- cursos de usuario -->
    <div class="user-cursos">
      <div class="user-cursos__head">
        <i class="fa fa-play-circle fa-2x" aria-hidden="true"></i>
        <p class="user-cursos__head__title">Mis cursos</p>
      </div>
      <div class="grid-x grid-margin-x user-cursos__items">
        {% for mc in my_courses %}
          <div class="cell small-12 medium-4 large-3">
            <div class="user-cursos__items__card">
              <img src="{{mc.course.image.url}}" alt="" class="user-cursos__items__card__img">
              <a href="{% url 'topicos_app:topicos-by_course' mc.course.category.slug mc.course.slug %}" class="user-cursos__items__card__name">{{mc.course.name}}</a>
              <p class="user-cursos__items__card__nivel">{{mc.course.get_nivel_display}}</p>
            </div>
          </div>
        {% empty %}
          <a href="{% url 'cursos_app:course-search' 'todos' %}" class="user-cursos__head__title">Aun no titne cursos, puede buscar cursos ...</a>
        {% endfor %}
      </div>
    </div>
    <!--  fin de cursos de usuario -->

    <!--  cursos relacionados -->
    <div class="user-relation-courses">
      <div class="relation-courses__head">
        <i class="fa fa-wpexplorer fa-2x" aria-hidden="true"></i>
        <p class="user-cursos__head__title">Tambien podrian interesarte estos cursos</p>
      </div>
      <div class="grid-x grid-margin-x relation-courses__items">
        {% for rc  in relation_courses  %}
          <div class="cell small-12 medium-4 large-3">
            <div class="user-cursos__items__card">
              <img src="{{rc.image.url}}" alt="" class="relation-courses__img">
              <a href="{% url 'cursos_app:course-detail' rc.category.slug rc.slug %}" class="relation-courses__name">{{rc.name}}</a>
              {% if rc.nivel == '0' %}
                <p class="course-card__etiqueta__nivel basico">Basico</p>
              {% elif rc.nivel == '1' %}
                <p class="course-card__etiqueta__nivel inter">Intermedio</p>
              {% else %}
                <p class="course-card__etiqueta__nivel avanzado">Avanzado</p>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <!--  fin cursos relacionados -->
  </div>
{% endblock %}

ncourses/templates/matriculas/pre-registro.html
{% extends "matriculas/base_matriculas.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Ademmy cursos online
{% endblock %}

{% block description %}
  {{user.first_name}} - {{user.last_name}}
{% endblock %}

{% block content %}
  {% include "include/menu.html" %}
  <!-- Inicio de grid pago -->
  <div class="grid-container">
    <div class="grid-x align-center">
      <div class="cell small-12 large-6 payment-header">
        <i class="fa fa-smile-o fa-4x" aria-hidden="true"></i>
        <p class="payment-header__title">{{curso.name}}</p>
        <p class="payment-header__subtitle">¿dudas? contacta a: ademmy.servicios@gmail.com ó envianos un wasapp a: 985124587</p>
      </div>
    </div>
    <div class="grid-x align-center">
      <div class="cell small-12 large-6 payment-content">
        <div class="payment-content__bancos">
          <h4 class="payment-content__bancos__title">Cuentas bancarias Disponibles</h4>
          <p class="payment-content__bancos__item">Bcp: 1234569874512</p>
          <p class="payment-content__bancos__item">Interbanck: 1234569874512</p>
          <p class="payment-content__bancos__item">otro banco: 1234569874512</p>
        </div>
        <div class="payment-content_amount">
          <p class="payment-content_amount__value">S/. 120.000</p>
          <p class="payment-content_amount__text">Despues de verificar el deposito se le activara el curso.</p>
        </div>
        <form class="payment-content__form" method="post">{% csrf_token %}
          {{form.banco}}
          {{form.cod_transaction}}  
          <input type="submit" class="payment-content__form__submit" value="Verificar">
        </form>
      </div>
    </div>
  </div>
  <!-- Fin de grid pago-->
  </div>
{% endblock %}