ncourses/applications/topicos/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para la aplicacion home
    url(
        r'^temas-de-curso/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.TopicoByCourseView.as_view(),
        name='topicos-by_course'
    ),
    # urls para ver una clase
    url(
        r'^cursos-clase/(?P<pk>\d+)/(?P<curso>\d+)/$',
        views.TopicoDetailView.as_view(),
        name='topicos-clase_view'
    ),
]

ncourses/ncourses/urls.py
"""ncourses URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # urls para la aplicacion home
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.home.urls', namespace="home_app")),
    url(r'^', include('applications.cursos.urls', namespace="cursos_app")),
    url(r'^', include('applications.topicos.urls', namespace="topicos_app")),
    url(r'^', include('applications.matriculas.urls', namespace="matriculas_app")),
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncourses/applications/topicos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# third-party
from model_utils.models import TimeStampedModel

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify

#applications cursos
from applications.cursos.models import Course

#local
from .managers import TopicosManager


@python_2_unicode_compatible
class Topico(TimeStampedModel):
    """ modelo para un tema o topicos """

    course = models.ForeignKey(
        Course,
        related_name='Curso',
    )
    name = models.CharField(
        blank=True,
        max_length=200
    )
    description = models.TextField(blank=True)
    minutes = models.CharField(
        blank=True,
        max_length=100
    )
    url_video = models.URLField(blank=True)

    objects = TopicosManager()

    class Meta:
        verbose_name = 'Clase'
        verbose_name_plural = 'Clases'

    def __str__(self):
        return self.name


    #funcion que se ejecuta al guardar
    def save(self, *args, **kwargs):
        #cambiammos el formato de video
        video = self.url_video.split('/')
        self.url_video = "https://www.youtube.com/embed/"+video[3]
        #
        super(Topico, self).save(*args, **kwargs)

ncourses/applications/topicos/views.py
# -*- coding: utf-8 -*-

# django
from django.views.generic import (
    DetailView,
    TemplateView,
    DeleteView,
    UpdateView,
    ListView,
)
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect

#app course
from applications.cursos.models import Course

# local
from .models import Topico


class TopicoByCourseView(ListView):
    """ lista de temas por curso """
    context_object_name = 'temas'
    template_name = 'topicos/list.html'

    def get_context_data(self, **kwargs):
        context = super(TopicoByCourseView, self).get_context_data(**kwargs)
        context['curso'] = Course.objects.get(slug=self.kwargs['slug'])
        return context

    def get_queryset(self):
        slug = self.kwargs['slug']
        queryset = Topico.objects.list_by_course(slug)
        return queryset


class TopicoDetailView(DetailView):
    """ vista que muestra el tema en reproducion de video """
    model = Topico
    template_name = 'topicos/clase.html'

    def get_context_data(self, **kwargs):
        context = super(TopicoDetailView, self).get_context_data(**kwargs)
        pk_curso = self.kwargs.get('curso', 0)
        curso = Course.objects.get(pk=pk_curso)
        context['curso'] = curso
        context['temas'] = Topico.objects.list_by_course(curso.slug)
        return context

ncourses/templates/topicos/base_topicos.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/scrips.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
{% endblock js %}

ncourses/templates/topicos/clase.html
{% extends "topicos/base_topicos.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Ademmy cursos online
{% endblock %}

{% block description %}
  {{user.first_name}} - {{user.last_name}}
{% endblock %}

{% block content %}
  {% include "include/menu.html" %}
  <div class="grid-x clase-head">
    <h1 class="clase-head__title">{{curso.name}} : {{object.name}}</h1>
  </div>
  <div class="grid-container">
    <div class="grid-x">
      <div class="cell small-12 large-8 clase-video">
        <iframe class="clase-video__frame"src="{{object.url_video}}" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="cell small-12 large-4 large-cell-block-y clase-list">
        <p class="clase-list__title">Videos del curso</p>
        <ul class="clase-list__guia">
          {% for t in temas %}
            <li class="clase-list__guia__item">
              <i class="fa fa-play-circle-o" aria-hidden="true"></i>
              <a href="{% url 'topicos_app:topicos-clase_view' t.pk curso.pk %}" class="clase-list__guia__item__name">{{t.name}}</a>
            </li>
          {% empty %}
            <p>Este curso aun no tiene clases</p>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="callout clase-description">
      <h4 class="clase-description__title">¿De que hablamos en esta clase?</h4>
      <p class="clase-description__content">{{object.description}}</p>
    </div>
  </div>
{% endblock %}

ncourses/templates/topicos/list.html
{% extends "topicos/base_topicos.html" %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Cursos online Ademmy
{% endblock %}

{% block description %}
  Cursos onlyne ademmy
{% endblock %}

{% block content %}

  <h1>Temas del curso</h1>
  {% for t in temas %}
    <p>{{t}}</p>

  {% endfor %}


{% endblock %}