ncourses/applications/users/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    # urls para registrar usuarios
    url(
        r'^registro/$',
        views.UserCreateView.as_view(),
        name='user-add'
    ),
    #url para login de usuarios
    url(
        r'^login/$',
        views.LogIn.as_view(),
        name='user-login'
    ),
    #url para cerrar sesion
    url(
        r'^salir/$',
        views.LogoutView.as_view(),
        name='logout'
    ),
    #url para redireccion
    url(
        r'^redirect/(?P<pk>\d+)/$',
        views.RedirectView.as_view(),
        name='redirect'
    ),
]

ncourses/ncourses/urls.py
"""ncourses URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # urls para la aplicacion home
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.home.urls', namespace="home_app")),
    url(r'^', include('applications.cursos.urls', namespace="cursos_app")),
    url(r'^', include('applications.topicos.urls', namespace="topicos_app")),
    url(r'^', include('applications.matriculas.urls', namespace="matriculas_app")),
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncourses/applications/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# third-party
from model_utils.models import TimeStampedModel

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)

#managers
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    TYPE_CHOICES = (
            ('0', 'Admin'),
            ('1', 'Docente'),
            ('2', 'Alumno'),
    )

    username = models.CharField('usuario', max_length=8, blank=True)
    type_user = models.CharField(
        'tipo de usuario',
        max_length=2,
        choices=TYPE_CHOICES,
        null=True,
        blank=True
    )
    email = models.EmailField('correo electronico', unique=True)
    first_name = models.CharField('nombres', max_length=50)
    last_name = models.CharField('apellidos', max_length=50)
    avatar = models.URLField(
        'foto',
        blank=True,
    )
    phone = models.CharField('telefono', max_length=50, blank=True, null=True)
    gender = models.CharField('sexo', max_length=1, choices=GENDER_CHOICES, blank=True)
    date_birth = models.DateField(blank=True, null=True)
    addresse = models.CharField('direccion',blank=True, max_length=100)

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', ]

    class Meta:
        verbose_name = 'usuario'
        verbose_name_plural = 'usuarios'

    def get_short_name(self):
        return self.email

    def get_full_name(self):
        return "%s %s" % (self.last_name, self.first_name)


@python_2_unicode_compatible
class Teacher(TimeStampedModel):
    """ modelo para profesor """

    user = models.ForeignKey(User)
    facebook = models.URLField(blank=True)
    linkedin = models.URLField(blank=True)
    porcentaje = models.CharField(
        blank=True,
        max_length=100
    )
    state = models.BooleanField(default=False)
    about = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'

    def __str__(self):
        return str(self.user.first_name)

ncourses/applications/users/forms.py
# -*- encoding: utf-8 -*-
from django import forms

from django.contrib.auth import authenticate

#app user
from .models import User


class LoginForm(forms.Form):

    email = forms.CharField(
        label='Email',
        max_length='100',
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email',
                'name':'email',
                'autofocus': 'autofocus',
            }
        ),
    )
    password = forms.CharField(
        label='contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'password',
            }
        ),
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('email o password incorrectos.')
        return self.cleaned_data


class UserAddForm(forms.ModelForm):
    """ formulario para registrar usuarios """

    password1 = forms.CharField(
        label='contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'password',
            }
        ),
    )
    password2 = forms.CharField(
        label='contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'password',
            }
        ),
    )

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
        )
        #
        widgets = {
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'Email',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombres...',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Apellidos...',
                }
            ),
        }

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            self.add_error('password2', 'las contraseñas no coinciden..!!')
        elif len(password2) < 5:
            print 'menor a 5 caracteres'
            self.add_error(
                'password2',
                'la contraseña debe tener por lo menos 5 caracteres!!'
            )
        else:
            return password2

ncourses/applications/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

#mixns
from applications.mixins import IsAutemticateMixin

# django
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    DetailView,
    TemplateView,
    DeleteView,
    UpdateView,
    ListView,
    CreateView,
    View
)
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

#app curso
from applications.cursos.models import Course

#app matriculas
from applications.matriculas.models import Registration
from applications.matriculas.functions import (
    create_matricula_free,
    create_update_registration
)

from .models import User
#
from .forms import UserAddForm, LoginForm


class UserCreateView(IsAutemticateMixin, CreateView):
    """ vista para registrar usuarios """

    template_name = 'users/register.html'
    success_url = reverse_lazy('matriculas_app:matricula-dashboard')
    form_class = UserAddForm

    def form_valid(self, form):
        #recuperamos el usuario y guardamos
        usuario = form.save(commit=False)
        password = form.cleaned_data['password1']
        usuario.set_password(password)
        usuario.type_user = '2'
        usuario.save()
        user = authenticate(
            username = form.cleaned_data['email'],
            password = form.cleaned_data['password1'],
        )
        return super(UserCreateView, self).form_valid(form)


class LogIn(IsAutemticateMixin, FormView):
    """ vista para acceso de usuarios login """

    template_name = 'users/login.html'
    success_url = '.'
    form_class = LoginForm

    def form_valid(self, form):
        print '*******************'
        # Verfiamos si el usuario y contrasenha son correctos.
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )

        if user is not None:
            if user.is_active and user.type_user == '2':
                login(self.request, user)
                return HttpResponseRedirect(
                    reverse(
                        'matriculas_app:matricula-dashboard'
                    )
                )
            else:
                return HttpResponseRedirect(
                    reverse(
                        'users_app:user-login'
                    )
                )

class LogoutView(View):
    """
    cerrar sesion
    """
    url = '/auth/login/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class RedirectView(LoginRequiredMixin, View):
    """ direccionar dependiendo de consulta """

    login_url = reverse_lazy('users_app:user-login')

    def get(self, request, *args, **kwargs):
        #recuperamos pk de curso
        pk_course = self.kwargs['pk']
        #recuperamos curso
        curso = Course.objects.get(pk=pk_course)
        #verificamos si ya esta matriculado
        if Registration.objects.filter(course=curso, activate=True).exists():
            return HttpResponseRedirect(
                reverse(
                    'matriculas_app:matricula-dashboard'
                )
            )
        elif curso.price == 0:
            create_matricula_free(curso, self.request.user)
            return HttpResponseRedirect(
                reverse(
                    'matriculas_app:matricula-dashboard'
                )
            )
        else:
            create_update_registration(curso, request.user)
            return HttpResponseRedirect(
                reverse(
                    'matriculas_app:matricula-preinscripcion',
                    kwargs={
                        'pk': curso.pk
                    },
                )
            )

        return self.render_to_response(self.get_context_data())

ncourses/templates/users/base_user.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
{% endblock js %}

ncourses/templates/users/login.html
{% extends "users/base_user.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Ademmy cursos online
{% endblock %}

{% block description %}
  Registrate para acceder a cursos de ingenieria
{% endblock %}

{% block content %}
  {% include "include/header.html" %}
  <!--  inicio de formulario de login  -->
  <div class="grid-container login-container">
    <div class="grid-x align-center login-container__form">
      <div class="cell small-12 medium-8 large-4 login-form">
        <p class="login-form__title">Ademmy</p>
        {% if form.errors %}
          <spam class="login-form__error">username o password incorrectos.</spam>
        {% endif %}
        <form class="login-form__input" method="post">{% csrf_token %}
          {{form.email}}
          {{form.password}}
          <input type="submit" class="login-form__input__btn" name="acceder" value="Acceder">
        </form>
        <a href="#" class="login-form__help">Olvide mi contraseña</a>
        <a href="{% url 'users_app:user-add' %}" class="login-form__registro">Registrarme</a>
      </div>
    </div>
  </div>
  <!--  fin de formulario de login  -->
{% endblock %}

ncourses/templates/users/register.html
{% extends "users/base_user.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Ademmy cursos online
{% endblock %}

{% block description %}
  Registrate para acceder a cursos de ingenieria
{% endblock %}

{% block content %}
  {% include "include/header.html" %}
  <!--  inicio de formulario de registro  -->
  <div class="grid-container register-container">
    <div class="grid-x align-center">
      <div class="cell small-12 large-8 register-form">
        <div class="grid-x">
          <div class="cell small-12 large-8">
            <form class="grid-x" method="post">{% csrf_token %}
              <div class="cell small-12 large-8">
                <label>Correo Electronico:</label>
                {{form.email}}
                {% for error in form.email.errors %}
                  <span style="color:red;">{{ error|escape }}</span>
                {% endfor %}
              </div>
              <div class="cell small-12 large-8">
                <label>Nombres:</label>
                {{ form.first_name}}
                {% for error in form.first_name.errors %}
                  <span style="color:red;">{{ error|escape }}</span>
                {% endfor %}
              </div>
              <div class="cell small-12 large-8">
                <label>Apellidos:</label>
                {{form.last_name}}
                {% for error in form.last_name.errors %}
                  <span style="color:red;">{{ error|escape }}</span>
                {% endfor %}
              </div>
              <div class="cell small-12 large-8">
                <label>Contraseña:</label>
                {{form.password1}}
              </div>
              <div class="cell small-12 large-8">
                <label>Repetir Contraseña:</label>
                {{form.password2}}
                {% for error in form.password2.errors %}
                  <span style="color:red;">{{ error|escape }}</span>
                {% endfor %}
              </div>
              <div class="cell small-12 large-8">
                <div class="grid-x align-center">
                  <div class="cell shrink">
                    <input type="submit" name="" class="button" value="Entrar">
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="cell small-12 large-4">
            <div class="register-recomendation">
              <i class="fa fa-id-card fa-3x" aria-hidden="true"></i>
              <p class="register-recomendation__text">Para acceder a cualquier curso de Ademmy, ud debe antes registrarse.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--  fin de formulario de registro  -->
{% endblock %}